#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=100:00:00
#PBS -N gen-mtcd-h
#PBS -o /home/samuroff/calibration/logs/gen-mtcd-h.log
#PBS -j oe

cd /home/samuroff/
python -m tools.im3shape.calibrate_all --calculate -c /home/samuroff/calibration/config/calibration_config_no_box_cut_matched_hoopoe.yaml
