#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=100:00:00
#PBS -N im3s-tomg
#PBS -o im3s-tomog.log
#PBS -j oe

cd /home/samuroff/
python -m tools.im3shape.calibrate_all_tomographic --calculate -c /home/samuroff/calibration_config_no_box_cut_tomographic.yaml

#python -m tools.im3shape.calibrate_all --catalogue -c /home/samuroff/calibration_config_no_box_cut.yaml

#python -m tools.im3shape.calibrate_all --weights -c /home/samuroff/calibration_config_no_box_cut.yaml 