#PBS -N build_covariance
#PBS -l nodes=1:ppn=16
#PBS -l walltime=18:00:00
#PBS -o /physics2/ssamurof/logs/build_covariance.log
#PBS -M ssamurof@andrew.cmu.edu
#PBS -q physics
#PBS -j oe

OUTDIR=cov-v7

cd /physics2/ssamurof/cosmosis/
mkdir -p $OUTDIR
mpiexec -n 16 python -m tools.des.build_cross_covariance.py --mpi --theory sws/ias/datavecs/simulated/fiducial/ --order sws/ias/datavecs/real/mcal-nongaussian/dvec-multiprobe-mcal-multicolour-NG-v7.fits --config desy1.yaml --outdir $OUTDIR