#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=60:00:00
#PBS -N toymodel-alpha
#PBS -o /home/samuroff/shear_pipeline/end-to-end/end-to-end_code/launch/logs/toymodel-alpha.log
#PBS -j oe


cd $SIMHOME
python -m tools.im3shape.toy_model